#!/bin/bash

./mill -i mill.contrib.sonatypecentral.SonatypeCentralPublishModule/publishAll \
    --username CiC1giTN \
    --password "$(pass infra/s01.oss.sonatype.org | head -n 1)" \
    --publishArtifacts __.publishArtifacts \
    --shouldRelease true
